#!/bin/bash

if [ -n "$1" ]; then
	export serial="-s $1"
else
	export serial=""
fi

./gradlew assembleDebug || exit 0

cp app/build/outputs/apk/debug/app-debug.apk . 

adb $serial shell cmd package uninstall -k ru.meteoinfo

adb $serial install app-debug.apk

adb $serial logcat -c

#adb shell am start -n ru.meteoinfo/.WeatherActivity

